### ISSUE TITLE
Add support for viewing Taranis/OpenTX logs

### ISSUE THREAD

**Issue by thenickdude** [cleanflight/blackbox-log-viewer#1]
Taranis/OpenTX collects much of the same data as the Blackbox, so it'd be useful to be able to read Taranis telemetry logs in the viewer.

**Comment by aequitas** [comment]
any progress on this? otherwise if you have a taranis logfile with most metrics represented i can look into it and make a pull request. I don't have any representable logs atm from my flights until i get telemetry running.

**Comment by kafie1980** [comment]
This would be useful for tuning whoops and micros that lack a blackbox logging by using OpenTX telemetry log data as a option.

**Comment by fedorcomander** [comment]
way to slow i think.
