### ISSUE TITLE
Hide/Show legend don't work without fields after browser restart.

### ISSUE THREAD

**Issue by Airwide** [cleanflight/blackbox-log-viewer#10]
After removing all the fields in the graph setup and restarting the browser the buttons to hide/show the legend don't work. It's working as long as you don't close the browser. The bug appears in Chrome/Firefox/Safari on Mac OS 10.10.3.

**Comment by fedorcomander** [comment]
Fixed. Pull req created.

**Comment by thenickdude** [comment]
Thanks, fixed by #11
