### ISSUE TITLE
Gyro data is no longer being displayed. Quad model is missing. 

### ISSUE THREAD

**Issue by ksal0** [cleanflight/blackbox-log-viewer#12]
Gyro data is no longer rendered. The new gyroADC data when rendered are basically strait lines and now useless.

Also the quad model is missing. 
1.9.0 pre release was good. 
This started with 1.9.0 stable
Image is at 1/1 sample rate

Reference cleanflight PR#998
https://github.com/cleanflight/cleanflight/pull/998

![blackbox new data](https://cloud.githubusercontent.com/assets/11943719/8024257/ed85d374-0d2d-11e5-8566-6b6a68d1d43f.jpg)

**Comment by SteveAmor** [comment]
Fixed Blackbox viewer in PR #13

**Comment by thenickdude** [comment]
Fixed now!
