### ISSUE TITLE
Ability to zoom in the timeline

### ISSUE THREAD

**Issue by borisbstyle** [cleanflight/blackbox-log-viewer#14]
It would be nice to be able to change reporing time interval to see more clearly differences between loop to loop and smaller ripples or even to zoom out to see the bigger picture.

**Comment by ledvinap** [comment]
Using blackbox_decode and then processing data in some other program will be easier if you are interested in detailed analysis ...

**Comment by borisbstyle** [comment]
Yes I know, but having this ability in log viewer would be nice.

**Comment by fedorcomander** [comment]
Not sure its what requested, but might be handy:

![screen shot 2015-06-10 at 16 59 10](https://cloud.githubusercontent.com/assets/2101514/8085890/cd91f752-0f92-11e5-90df-7dd7a3549495.png)

**Comment by fedorcomander** [comment]
And zoom in.

![screen shot 2015-06-10 at 17 05 43](https://cloud.githubusercontent.com/assets/2101514/8085904/f9428d9e-0f92-11e5-8f2e-905b11199051.png)

**Comment by borisbstyle** [comment]
@fedorcomander 
Yes that's exactly what I meant!

**Comment by hydra** [comment]
Oops wrong button

**Comment by hydra** [comment]
+1

**Comment by thenickdude** [comment]
Merged.
