### ISSUE TITLE
Allow user to select graph line thickness

### ISSUE THREAD

**Issue by hydra** [cleanflight/blackbox-log-viewer#16]
With the laptop in the field on a sunny day i find it very hard to see the lines.  Thicker lines would help.

**Comment by thenickdude** [comment]
Until a configuration dialog for this is added, I've added a PLOT_LINE_WIDTH constant so you can tune it manually in the source:

https://github.com/cleanflight/blackbox-log-viewer/blob/master/js/grapher.js#L19

**Comment by timdonovanuk** [comment]
Changing this constant doesn't seem to do anything for me. Have tried values 0.5, 0.9, 5, 50, 100.

**Comment by timdonovanuk** [comment]
It seems whatever value you put in the constant its immediately overwritten on line 665 with plotLineWidth:             Math.max(1.25, canvas.height / 400)

If you want to make the line thicker edit line 444,  canvasContext.lineWidth = yourvalue

**Comment by McGiverGim** [comment]
This was done long time ago. I close the issue.
