### ISSUE TITLE
Add graph setup profiles

### ISSUE THREAD

**Issue by joshuabardwell** [cleanflight/blackbox-log-viewer#19]
I have several common setups that I use for analysis. It'd be nice to be able to switch between them without having to manually set them up every time.

**Comment by bryanpearson** [comment]
+1 This would be quite handy. I have a hacked version for my own use, but I'm not a great coder, so some other JS genius would need to bust it out

**Comment by BryceMindLab** [comment]
I also believe this would be an amazing feature!

**Comment by McGiverGim** [comment]
@joshuabardwell I think this is already included in the actual version. You can save the workspace settings and you can save the the actual graphs selection with "shift+number" and recovered with "number".

Can I close this issue?
