### ISSUE TITLE
Error opening log: No logs in this file could be parsed successfully

### ISSUE THREAD

**Issue by ralphreijs** [cleanflight/blackbox-log-viewer#25]
Hi, on both blackbox_decode and the blackbox-log-viewer, i am getting the following message when i open one of the .TXT files from my Blackbox SD card:

Error opening log: No logs in this file could be parsed successfully

I can't seem to get the tool to accept any of the files, yet they are a few hundred kilobytes big. My looptime is 1600, is that too low? i've seen a proper looking logfile and mine looks totally garbled.
Thanks.

![screen shot 2015-06-30 at 23 16 58](https://cloud.githubusercontent.com/assets/203897/8442291/6b333c6e-1f7e-11e5-859d-677427e4e605.png)
![screen shot 2015-06-30 at 23 16 20](https://cloud.githubusercontent.com/assets/203897/8442292/6b51d3cc-1f7e-11e5-86b5-25b3a215326c.png)
![screen shot 2015-06-30 at 23 20 32](https://cloud.githubusercontent.com/assets/203897/8442339/b46401fc-1f7e-11e5-99a3-da70a9f9ad8b.png)

**Comment by thenickdude** [comment]
That log file is actually MSP data, did you connect the logger to the wrong serial port? Post your ports configuration.

**Comment by ralphreijs** [comment]
Ahh that was it, I only had the checkbox "MSP" checked for UART1, after checking "Blackbox" checkbox, it now logs properly :) thanks a lot, sorry for the noob question, didn't realize i needed to do that as well.

**Comment by thenickdude** [comment]
No problem!
