### ISSUE TITLE
add acceleration (and maybe estimated speed) graphic

### ISSUE THREAD

**Issue by MauroMombelli** [cleanflight/blackbox-log-viewer#35]
if the log data contain heading we can estimate the G vector, and subract it to the acceeleration vector, so we get the real acceleration along the 3 axis.

Integrating those acceleration also give a rough estimation of the speed, that would be nice to have.

**Comment by thenickdude** [comment]
That acceleration data is currently plotted by the commandline tool blackbox_render if you want it right away.

I think the acceleration integration will drift so quickly as to be worthless for velocity estimation.
