### ISSUE TITLE
Startup Screen All Links are broken

### ISSUE THREAD

**Issue by mehmetyldz87** [cleanflight/blackbox-log-viewer#37]
Under "Introduction to Blackbox" , "Tuning your carft", and "Other Tools" Tabs, all links are broken.

Thanks

**Comment by AustinSaintAubin** [comment]
I am having a similar / the same issue.
All the links on the main start page do links when clicked.
Mac OS X 10.11.3, Chome Version 48.0.2564.116 (64-bit)
