### ISSUE TITLE
Plus quad not supported in viewer

### ISSUE THREAD

**Issue by lazd** [cleanflight/blackbox-log-viewer#39]
I recently got some logs tearing around in [my Mitsuko](http://imgur.com/a/NoaGw) and found there is no way to change the visualization from a X quad to a + quad. This would be helpful in visualizing how much the rear motor is working to providing forward thrust.

It's clear the rear motor (1 on the + quad) corresponds to the back left motor (1 on the X quad), of course, but it would be nice if the visualization matched the data.

![screen shot 2015-12-10 at 12 39 50 am](https://cloud.githubusercontent.com/assets/201344/11710794/9b03ef24-9ed6-11e5-99c0-cbf948b954be.png)

**Comment by AustinSaintAubin** [comment]
I have a similar issue with tuning my airplane & flying wing, the blackbox view shows it as a quad motor.
Would like to see servo values rendered on an airplane airframe. This graph shows me nothing about what the servo's are doing.

The [2D Craft](https://github.com/cleanflight/blackbox-log-viewer/blob/master/js/craft_2d.js) & [3D Carft](https://github.com/cleanflight/blackbox-log-viewer/blob/master/js/craft_3d.js) files need to be modified to add additional aircraft models. But before that, the Blackbox viewer needs a way to know what type of craft the blackbox data is from.
Could the flight controller report the aircraft configuration in the blackbox data?
If the flight controller can report the aircraft configuration then the viewer can use that to determine it and render the correct model. Could use a [FlightLogEvent](https://github.com/cleanflight/blackbox-log-viewer/blob/6014c05c8f5db06a8bf765594d869f5187df9896/js/flightlog_fielddefs.js) at the start of each logging session.
