### ISSUE TITLE
In Firefox, Playback stops when trying to jump to a certain spot in the graph

### ISSUE THREAD

**Issue by Arakon** [cleanflight/blackbox-log-viewer#4]
When attempting to click the graph below the main window in Firefox (Windows 7, 37.0.1), most of the time, playback stops as if it was reset to the beginning and paused, the red bar disappears, and playback can not be resumed. Seemingly at random, it does work to skip to the spot in the graph, but only rarely and not the same spot twice. Also, the index timer in the bottom right displays NaN:NaN:NaN when this happens.
![ff](https://cloud.githubusercontent.com/assets/12016360/7218755/21b0777e-e67f-11e4-952b-a4e0c2fcd5a3.jpg)

None of this occurs with Chrome, using the exact same log file and exact same log viewer.

**Comment by thenickdude** [comment]
Thanks for the report, this should be fixed now. Please try the latest version and let me know if it still doesn't work!

**Comment by Arakon** [comment]
Indeed, appears to be working just fine now.
