### ISSUE TITLE
Flight reported total current draw

### ISSUE THREAD

**Issue by dronehitech** [cleanflight/blackbox-log-viewer#40]
Hello guys, is it possible to add a feature showing the total reported current draw for a flight/log?

**Comment by joshuabardwell** [comment]
You mean mAh?

**Comment by dronehitech** [comment]
yes

**Comment by fedorcomander** [comment]
Do u have real current meter?

**Comment by dronehitech** [comment]
yes, the Arsov ACSP3 voltage/current sensor.

**Comment by dronehitech** [comment]
What do you mean guys, possible? I think its useful.
