### ISSUE TITLE
Add support for logging/viewing actual stick positions, in addition to rcCommand

### ISSUE THREAD

**Issue by joshuabardwell** [cleanflight/blackbox-log-viewer#42]
rcCommand is after rc expo and also features like roll yaw uptilt compensation. Would be nice to be able to log actual stick positions for training, as well as configure the viewer to show either stick positions or rcCommand (or both at the same time, for comparison?).

**Comment by McGiverGim** [comment]
@joshuabardwell This issue is pretty old, and I think that what you ask for is already in the actual version. Is that true? Can I close the issue?
