### ISSUE TITLE
exported video file size

### ISSUE THREAD

**Issue by yosemitez** [cleanflight/blackbox-log-viewer#51]
taking gp4 file and rendering it to 966x540 60fps, that 5 min file comes out to 137mb

import it into bblv and render at 720 and the file is  1.03 gig

any hints on how to reduce exported file size?

**Comment by thenickdude** [comment]
In JavaScript, we're basically stuck with it because we have to render what
is basically a series of single frames as separate images. This doesn't
allow for very advanced compression.

Now that we're available as a desktop app we may be able to integrate with
ffmpeg to render to H.264 directly.

**Comment by yosemitez** [comment]
thanks!  will just bring it back into sony vegas and rerender to a more manageable size
