### ISSUE TITLE
unable to open spectrum analyser

### ISSUE THREAD

**Issue by krzysztofmatula** [cleanflight/blackbox-log-viewer#53]
I use the latest blackbox explorer (9333f41).

I open a log file and it can be seen, however the "View/hide analyser display" doesn't seem to work at all. When clicked, the window is not shown and the icon doesn't turn yellow.

Did it change? It used to work for me some time ago...
How to debug it further?

**Comment by thenickdude** [comment]
We don't have a spectrum analyser, you must be using Betaflight's log viewer instead.
