### ISSUE TITLE
How open or cut large 16MB LOG file? Crash App when try open.

### ISSUE THREAD

**Issue by kszere** [cleanflight/blackbox-log-viewer#84]
I using FC `KAKUTE V2` with BT v3.3.0. Flash size for LOG data is 16MB. When I try opening this file, Chrome Crasching or MSG BOX `Page Unresponsive`.

blackbox-tools also can't read - `blackbox-decode`

How cut this file for few smallest?

**Comment by trendab** [comment]
My Kakute logs are also not opening most of the time. Some very small ones sometimes open. Is this a BB or a firmware issue?
