### ISSUE TITLE
Enhancement Request: Ability to use blackbox data to stabilize associated video

### ISSUE THREAD

**Issue by dngrlux** [cleanflight/blackbox-log-viewer#9]
Wondering if it would be feasible to utilize the blackbox data to assist with video stabilization within the viewer, or produce some kind of transform/tracking information that can then be used in post, such as After Effects or Final Cut Pro X, to save time or produce better results. I see some information at http://www.google.com/patents/US8488010, so people have done similar research prior to this idea.

**Comment by thenickdude** [comment]
You can use `blackbox_decode` to produce degrees-per-second information for each axis which could be used to do that. There's no current plans for Blackbox to perform the video processing itself, but if you have a video editing package which takes rotation data as input for stabilisation, let me know the format.
